
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import platform
import psutil
import wmi
import cpuinfo
from pathlib import Path
import speedtest

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from tkinter.messagebox import showerror, showwarning, showinfo


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title("Проверка системы ВЕБ КЦ Монастырев")
window.geometry("640x480")
window.configure(bg = "#FFFFFF")
computer = wmi.WMI()
gpu_info = computer.Win32_VideoController()[0]
ram_gb = psutil.virtual_memory().total / (1024**3)
disk_space_gb = psutil.disk_usage('C:\\').free / (1024**3)
cpuname = cpuinfo.get_cpu_info()['brand_raw']
speeddw = 10.1



canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 360,
    width = 540,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    270.0,
    180.0,
    image=image_image_1
)

canvas.create_rectangle(
    11.0,
    146.0,
    372.0,
    323.0,
    fill="#F8F7F7",
    outline="")

canvas.create_text(
    22.0,
    210.0,
    anchor="nw",
    text=f"Программа для проверки минимальных\nСистемных требований вашего ПК\nДля установки программы веб КЦ",
    fill="#7D7D7D",
    font=("Inter Black", 12 * -1)

)
    
    
def check_network():
    showinfo(title="Информация", message="Во время проверки не отключайте ваш ПК и не закрывайте приложение")
    st = speedtest.Speedtest()
    speed = st.download()
    best = st.get_best_server()
    btn.pack_forget()
    sp = int(speed / (1024 * 1024))
    print(sp)
    

    canvas.create_rectangle(
    11.0,
    146.0,
    372.0,
    323.0,
    fill="#F8F7F7",
    outline="")

    canvas.create_text(
    22.0,
    180.0,
    anchor="nw",
    text=f"Имя компьютера: {platform.node()}\nАрхитектура: {platform.architecture()}\nОС: {platform.platform()}\nПроцессор: {cpuname}\nГрафика: {format(gpu_info.Name)}\nОперативная память: {ram_gb:.0f} GB\nИнтернет скорость: {float(speed / (1024 * 1024)):.0f} Mb/s",
    fill="#7D7D7D",
    font=("Inter Black", 12 * -1)
    
)
    
    canvas.create_text(
    130.0,
    152.0,
    anchor="nw",
    text="Характеристики вашего ПК:",
    fill="#000000",
    font=("Inter Black", 12 * -1)
)

    showinfo(title="Информация", message="Проверка выполнена")

    if ram_gb < 8:
        canvas.create_text(
        22.0,
        290.0,
        anchor="nw",
        text="Внимание: Недостаточно оперативной памяти.",
        fill="#FF0000",
        font=("Inter Black", 12 * -1)
    )
    elif sp < 60:
        canvas.create_text(
        22.0,
        305.0,
        anchor="nw",
        text="Внимание: Ваша интернет скорость ниже 60 Mb/s",
        fill="#FF0000",
        font=("Inter Black", 12 * -1)
        )

    elif disk_space_gb < 20:
        canvas.create_text(
        22.0,
        315.0,
        anchor="nw",
        text="Внимание: Недостаточно места на жестком диске.",
        fill="#FF0000",
        font=("Inter Black", 12 * -1)
        )
    
    else:    
            canvas.create_text(
            130.0,
            300.0,
            anchor="nw",
            text="ВСЕ ОТЛИЧНО!",
            fill="#00FF0A",
            font=("Inter Black", 12 * -1)
        )
    
    return speed

btn = Button(window,width=400,height=2, text="Проверить ПК", command=check_network)
btn.pack()






window.resizable(False, False)
window.mainloop()
